{{- if and .Values.configuration.enabled (eq .Values.configuration.existingConfigMap "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-configuration
  namespace: {{ include "home-assistant.namespace" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- tpl .Values.configuration.templateConfig . | nindent 4 }}
{{- end -}}
