apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "home-assistant.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- if .Values.hostNetwork }}
      hostNetwork: true
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.dnsConfig }}
      dnsConfig: 
        {{- toYaml .Values.dnsConfig | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
              {{- if .Values.hostPort.enabled }}
              hostPort: {{ .Values.hostPort.port }}
              {{- end }}
          {{- if .Values.additionalPorts }}
            {{- .Values.additionalPorts | toYaml | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - mountPath: /config
            name: {{ include "home-assistant.fullname" . }}
          {{- if .Values.additionalMounts }}
            {{- .Values.additionalMounts | toYaml | nindent 10 }}
          {{- end }}
        {{- if .Values.addons.codeserver.enabled }}
        - name: codeserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
          - --auth
          - none
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
          - --port
          - "12321"
          - "/config"
          image: "{{ .Values.addons.codeserver.image.repository }}:{{ .Values.addons.codeserver.image.tag }}"
          imagePullPolicy: "{{ .Values.addons.codeserver.image.pullPolicy }}"
          ports:
          - containerPort: 12321
            name: codeserver
            protocol: TCP
          {{- with .Values.addons.codeserver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - mountPath: /config
            name: {{ include "home-assistant.fullname" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      {{- if not .Values.persistence.enabled }}
      - name: {{ include "home-assistant.fullname" . }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.additionalVolumes }}
        {{- .Values.additionalVolumes | toYaml | nindent 6 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "home-assistant.fullname" . }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.existingVolume }}
      volumeName: {{ .Values.persistence.existingVolume }}
      {{- end }}
      {{- if or .Values.persistence.matchLabels (.Values.persistence.matchExpressions) }}
      selector:
      {{- if .Values.persistence.matchLabels }}
        matchLabels:
        {{ toYaml .Values.persistence.matchLabels | indent 8 }}
      {{- end -}}
      {{- if .Values.persistence.matchExpressions }}
        matchExpressions:
          {{ toYaml .Values.persistence.matchExpressions | indent 8 }}
        {{- end -}}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
  {{- end }}
  
