ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: homeassistant.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: homeassistant-tls
      hosts:
        - homeassistant.example.com
